### ISSUE TITLE
Request Korean distribution

### ISSUE THREAD

**Issue by Violet-Bora-Lee** [javascript-tutorial/en.javascript.info#1602]
Hello, Ilya and the Team!

The modern JavaScript tutorial in Korean is almost ready to publish(Part 1 is translated, almost), finally! 👍 👍 👍 
https://github.com/javascript-tutorial/en.javascript.info/issues/1149  

Please let me know what I need to do to publish the Korean ver.

**Comment by iliakan** [comment]
Great news! Mentioning @javascript-tutorial/translate-ko =)

Makes sense to translate site UI then.

Please clone https://github.com/javascript-tutorial/server, find all `en.yml` and put translated `ko.yml` alongside them, similar to other languages that you'll see there.

Then make a PR with this change. 

P.S. `./edit ko ko` runs the tutorial with Korean language files.

**Comment by Violet-Bora-Lee** [comment]
I've made 2 PR on engine and server repositories.

https://github.com/javascript-tutorial/engine/pull/26
https://github.com/javascript-tutorial/server/pull/48

**Comment by iliakan** [comment]
A few more phrases please:
```
terms: terms of usage
last_updated_at: "Last updated at #{date}"
contributors_pluralize: "contributor,contributors,contributors"

// search
articles: Articles of the tutorial
tasks: Tasks
results: Search results
search: Search
find: Find

shown_only_results: "Only first #{count} results are shown."

not_found:
  prefix: Sorry, we couldn't find anything
  articles: in the articles of the tutorial
  tasks: in the tasks
```

**Comment by iliakan** [comment]
just post them here =) thank you!

**Comment by Violet-Bora-Lee** [comment]
```
terms: 이용 약관
last_updated_at: "최종 업데이트 #{date}"
contributors_pluralize: "contributor,contributors,contributors"

// search
articles: 글
tasks: 과제
results: 검색 결과
search: 검색
find: 찾기

shown_only_results: "#{count} 개의 검색 결과만 보기"

not_found:
  prefix: 죄송합니다.
  articles: 원하는 글을 찾지 못했습니다.
  tasks: 원하는 과제를 찾지 못했습니다.
```

**Comment by iliakan** [comment]
contributors_pluralize: "contributor,contributors,contributors" . ?

**Comment by Violet-Bora-Lee** [comment]
```
terms: 이용 약관
last_updated_at: "최종 업데이트 #{date}"
contributors_pluralize: "기여자,기여자,기여자"

// search
articles: 글
tasks: 과제
results: 검색 결과
search: 검색
find: 찾기

shown_only_results: "#{count} 개의 검색 결과만 보기"

not_found:
  prefix: 죄송합니다.
  articles: 원하는 글을 찾지 못했습니다.
  tasks: 원하는 과제를 찾지 못했습니다.
```
